redis:
  image: redis
  command: redis-server --appendonly yes
  ports:
    - '6379'
  log_driver: syslog
  volumes_from:
    - redis_data
stream:
  image: quay.io/loggingroads/planet-stream:latest
  env_file: .env
  links:
    - redis
    - forgettable
  log_driver: syslog
api:
  image: quay.io/loggingroads/osm-stats-api:latest
  links:
    - redis
    - forgettable
  ports:
    - 80:3000
  env_file: .env
  log_driver: syslog
forgettable:
  image: quay.io/loggingroads/forgettable:latest
  ports:
    - 8080:8080
  links:
    - redis
  log_driver: syslog
redis_data:
  image: alpine
  command: "true"
  volumes:
    - ./redis_data:/data
